FROM mysql:latest

COPY mysql.sql /docker-entrypoint-initdb.d/mysql.sql

 ENV MYSQL_ROOT_PASSWORD your_password
 ENV MYSQL_DATABASE mydatabase

EXPOSE 3306

CMD  ["--default-authentication-plugin=mysql_native_password"]
