name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Install Composer dependencies
        run: |
         curl -sS https://getcomposer.org/installer | php --
         mv composer.phar /usr/local/bin/composer
         composer install

      - name: Build and test PHP code
        run: |
         # Run PHPUnit tests using Docker Compose
         docker-compose -f docker-compose.test.yml up --exit-code-from test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: irehankhan/my-php-app:1.0